spring:
  application:
    name: tradeIdea
  data:
    mongodb:
      uri: mongodb://localhost:27017/tradingdb


futu:
  api:
    base-url: https://openapi.futunn.com  # Replace with the actual base URL
    api-key: your-api-key-here  # Replace with your actual API key
    snapshot-endpoint: /futu-api/market-snapshot
    symbols:
      - NVIDA
    fetch-interval-ms: 300000  # 5 minutes